module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/I1YS1AeKFiNBN1wnl6Z6tg?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/XkyWNN4Q/tourl-1765878318885.jpg',
    NEWSLETTER_JID: '120363406176407309@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐒𝐀𝐒𝐀 𝐗 𝐌𝐃',
    OWNER_NAME: 'Sasanka Chamuth',
    OWNER_NUMBER: '94784167385',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> 𝚂𝙰𝚂𝙰 𝙼𝙸𝙽𝙸 𝙱𝙾𝚃 𝚅1 - </> 𝙿𝙾𝚆𝙴𝚁𝙳 𝙱𝚈 𝚂𝙰𝚂𝙰 𝙲𝙾𝙳𝙴𝚁 ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb7P18V84OmA7pIqw03U',
};
//💋
